name = "betledger-pro"
compatibility_date = "2026-07-21"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "betledger-db"
database_id = "5e7ddd3c-12b4-4244-9f58-8b723d9dff30"
