
let DATA_KEY='betledger_guest_bets',SETTINGS_KEY='betledger_guest_settings';
let bets=[],settings={startingBankroll:1000,unitSize:10},editingId=null,currentUser=null;
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0)),pct=n=>`${Number(n||0).toFixed(1)}%`,uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
let storageAvailable=true,cloudTimer=null,cloudBusy=false,cloudPending=false,cloudPollTimer=null;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{storageAvailable=false;return f}}
function localMetaKey(){return `${DATA_KEY}_cloud_updated`}
function pendingKey(){return `${DATA_KEY}_pending_sync`}
function setUserStorage(user){DATA_KEY=`betledger_${user}_bets_v27`;SETTINGS_KEY=`betledger_${user}_settings_v27`;bets=load(DATA_KEY,[]);settings=load(SETTINGS_KEY,{startingBankroll:1000,unitSize:10});cloudPending=localStorage.getItem(pendingKey())==='1'}
function saveLocalOnly(){try{localStorage.setItem(DATA_KEY,JSON.stringify(bets));localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));storageAvailable=true;return true}catch(err){storageAvailable=false;console.error(err);return false}}
function save(){const ok=saveLocalOnly();cloudPending=true;try{localStorage.setItem(pendingKey(),'1')}catch{}queueCloudSync();return ok}
function setCloudStatus(label,state=''){if($('cloudLabel'))$('cloudLabel').textContent=label;if($('cloudDot'))$('cloudDot').className=`cloud-dot ${state}`;if($('cloudNotice'))$('cloudNotice').textContent=label}
async function api(path,options={}){const r=await fetch(`/api/${path}`,{credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function queueCloudSync(delay=750){if(!currentUser)return;clearTimeout(cloudTimer);setCloudStatus(navigator.onLine?'Saving…':'Pending sync',navigator.onLine?'':'offline');cloudTimer=setTimeout(pushCloudState,delay)}
async function pushCloudState(){if(!currentUser||cloudBusy||!cloudPending)return;if(!navigator.onLine){setCloudStatus('Pending sync — offline','offline');return}cloudBusy=true;setCloudStatus('Saving…');try{const result=await api('state',{method:'PUT',body:JSON.stringify({bets,settings})});cloudPending=false;localStorage.removeItem(pendingKey());localStorage.setItem(localMetaKey(),String(result.updatedAt||Date.now()));setCloudStatus('Saved to Cloudflare','online')}catch(err){cloudPending=true;setCloudStatus(`Sync failed — will retry: ${err.message}`,'offline')}finally{cloudBusy=false;if(cloudPending&&navigator.onLine)queueCloudSync(5000)}}
async function pullCloudState(force=false){if(!currentUser||cloudBusy)return;setCloudStatus('Loading from Cloudflare…');try{const data=await api('state');const remote=data.state;const localUpdated=+(localStorage.getItem(localMetaKey())||0);if(remote){if(force||(!cloudPending&&remote.updatedAt>localUpdated)){bets=Array.isArray(remote.bets)?remote.bets:[];settings={startingBankroll:1000,unitSize:10,...remote.settings};saveLocalOnly();localStorage.setItem(localMetaKey(),String(remote.updatedAt));syncSettings();render()}else if(cloudPending){await pushCloudState()}setCloudStatus(cloudPending?'Pending sync':'Saved to Cloudflare',cloudPending?'offline':'online')}else if(bets.length||cloudPending){cloudPending=true;await pushCloudState()}else{cloudPending=true;await pushCloudState()}}catch(err){setCloudStatus(`Offline cache — ${err.message}`,'offline')}}
function startCloudPolling(){clearInterval(cloudPollTimer);cloudPollTimer=setInterval(()=>{if(document.visibilityState==='visible'){cloudPending?pushCloudState():pullCloudState(false)}},20000)}
async function establishSession(user){currentUser=user;setUserStorage(user);$('loginGate').classList.add('hidden');$('userChip').textContent=user[0].toUpperCase()+user.slice(1);$('userChip').classList.remove('hidden');syncSettings();render();await pullCloudState(false);startCloudPolling()}
async function initCloud(){try{const data=await api('session');if(data.user)await establishSession(data.user);else $('loginGate').classList.remove('hidden')}catch{$('loginGate').classList.remove('hidden')}}
addEventListener('online',()=>{setCloudStatus('Back online — syncing…');cloudPending?pushCloudState():pullCloudState(false)});
addEventListener('offline',()=>setCloudStatus('Pending sync — offline','offline'));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&currentUser){cloudPending?pushCloudState():pullCloudState(false)}});
function toast(message,type='success'){const el=$('toast');el.textContent=message;el.className=`toast ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),3200)}function validateBetForm(){document.querySelectorAll('.field-error').forEach(x=>x.remove());const checks=[['event','Enter the event or matchup.'],['selection','Enter your betting selection.'],['odds','Enter valid American odds, such as -110 or +125.'],['stake','Enter a stake greater than $0.']];let first=null;for(const [id,msg] of checks){const el=$(id),invalid=id==='odds'?(!el.value||+el.value===0):id==='stake'?(!el.value||+el.value<=0):!el.value.trim();if(invalid){const note=document.createElement('div');note.className='field-error';note.textContent=msg;el.closest('.field').appendChild(note);first??=el}}if(first){first.focus();toast('Please complete the highlighted fields.','error');return false}return true}

function potential(stake,odds){stake=+stake;odds=+odds;if(!stake||!odds)return 0;return odds>0?stake*odds/100:stake*100/Math.abs(odds)}function pl(b){if(b.result==='Win')return +b.payout-+b.stake;if(b.result==='Loss')return -+b.stake;return 0}function decimalOdds(o){o=+o;if(!o)return 0;return o>0?1+o/100:1+100/Math.abs(o)}function clv(b){if(!b.closingOdds||!b.odds)return null;return (decimalOdds(b.odds)/decimalOdds(b.closingOdds)-1)*100}function cls(n){return n>0?'positive':n<0?'negative':''}function signed(n){return `${n>0?'+':''}${money(n)}`}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function dateFmt(s){return new Date(`${s}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'2-digit'})}
function settled(list=bets){return list.filter(b=>b.result!=='Pending')}function stats(list=bets){const s=settled(list),wins=s.filter(b=>b.result==='Win').length,losses=s.filter(b=>b.result==='Loss').length,pushes=s.filter(b=>b.result==='Push').length,stake=s.reduce((a,b)=>a+(b.result==='Push'?0:+b.stake),0),profit=s.reduce((a,b)=>a+pl(b),0),pending=list.filter(b=>b.result==='Pending').reduce((a,b)=>a+ +b.stake,0),decisions=wins+losses;return{s,wins,losses,pushes,stake,profit,pending,roi:stake?profit/stake*100:0,winRate:decisions?wins/decisions*100:0,currentBankroll:+settings.startingBankroll+profit,units:+settings.unitSize?profit/+settings.unitSize:0}}
function groupBy(field,list=bets){const map={};settled(list).forEach(b=>{const k=b[field]||'Unspecified';(map[k]??=[]).push(b)});return Object.entries(map).map(([name,arr])=>({name,...stats(arr),count:arr.length})).sort((a,b)=>b.profit-a.profit)}
function rankHTML(items,limit=6){if(!items.length)return '<div class="empty">No settled data yet.</div>';return items.slice(0,limit).map(x=>`<div class="rank-item"><div><div class="rank-name">${esc(x.name)}</div><div class="rank-meta">${x.wins}-${x.losses}${x.pushes?`-${x.pushes}`:''} · ${pct(x.roi)} ROI · ${x.count} bets</div></div><div class="rank-value ${cls(x.profit)}">${signed(x.profit)}</div></div>`).join('')}
function renderMetrics(){const s=stats();const items=[['Current Bankroll',money(s.currentBankroll),cls(s.profit),`Started ${money(settings.startingBankroll)}`],['Net P/L',signed(s.profit),cls(s.profit),`${s.units>=0?'+':''}${s.units.toFixed(2)} units`],['ROI',pct(s.roi),cls(s.roi),`${money(s.stake)} settled stake`],['Win Rate',pct(s.winRate),s.winRate>=52?'positive':'',`${s.wins}-${s.losses}-${s.pushes}`],['Pending Risk',money(s.pending),s.pending?'neutral':'',`${bets.filter(b=>b.result==='Pending').length} open bets`],['Avg Stake',money(s.s.length?s.stake/s.s.length:0),'',`Unit: ${money(settings.unitSize)}`],['Avg Odds',s.s.length?`${Math.round(s.s.reduce((a,b)=>a+ +b.odds,0)/s.s.length)>0?'+':''}${Math.round(s.s.reduce((a,b)=>a+ +b.odds,0)/s.s.length)}`:'—','accent','Settled wagers'],['CLV',avgClv()==null?'—':pct(avgClv()),avgClv()>0?'positive':avgClv()<0?'negative':'','Average available CLV']];$('metrics').innerHTML=items.map(([l,v,c,sub])=>`<article class="metric"><label>${l}</label><strong class="${c}">${v}</strong><small>${sub}</small></article>`).join('')}
function avgClv(){const vals=settled().map(clv).filter(v=>v!==null&&Number.isFinite(v));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function renderPulse(){const s=stats(),bankrollChange=settings.startingBankroll?s.profit/settings.startingBankroll*100:0,goal=Math.min(100,Math.max(0,50+s.roi));let best=groupBy('sport')[0];$('pulse').innerHTML=`<div class="progress-row"><div class="progress-top"><span>Bankroll change</span><strong class="${cls(bankrollChange)}">${bankrollChange>=0?'+':''}${pct(bankrollChange)}</strong></div><div class="progress"><span style="width:${Math.min(100,Math.max(0,50+bankrollChange))}%"></span></div></div><div class="progress-row"><div class="progress-top"><span>ROI score</span><strong class="${cls(s.roi)}">${pct(s.roi)}</strong></div><div class="progress"><span style="width:${goal}%"></span></div></div><div class="insight">${best?`Your strongest category is <strong>${esc(best.name)}</strong> at ${signed(best.profit)} and ${pct(best.roi)} ROI.`:'Settle more wagers to generate performance insights.'}</div><div class="insight">${s.pending?`${money(s.pending)} is currently exposed across pending wagers.`:'You have no pending bankroll exposure.'}</div>`}
function renderRanks(){const sports=groupBy('sport'),markets=groupBy('betType'),books=groupBy('sportsbook'),timing=groupBy('timing');$('bestSports').innerHTML=rankHTML(sports,4);$('bestMarkets').innerHTML=rankHTML(markets,4);$('bestBooks').innerHTML=rankHTML(books,4);$('sportRanks').innerHTML=rankHTML(sports,20);$('marketRanks').innerHTML=rankHTML(markets,20);$('bookRanks').innerHTML=rankHTML(books,20);$('timingRanks').innerHTML=rankHTML(timing,20)}
function renderChart(){const data=settled().sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt),c=$('profitChart'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,r.width,r.height);$('chartCount').textContent=`${data.length} settled bets`;$('chartEmpty').classList.toggle('hidden',!!data.length);if(!data.length)return;let run=+settings.startingBankroll;const pts=data.map(b=>({date:b.date,value:run+=pl(b)})),vals=[+settings.startingBankroll,...pts.map(p=>p.value)],pad={l:66,r:18,t:20,b:38},w=r.width-pad.l-pad.r,h=r.height-pad.t-pad.b;let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=10;max+=10}const m=(max-min)*.12;min-=m;max+=m;const xx=i=>pad.l+(pts.length===1?w/2:i/(pts.length-1)*w),yy=v=>pad.t+(max-v)/(max-min)*h;x.font='12px system-ui';for(let i=0;i<=4;i++){const v=max-(max-min)*i/4,y=pad.t+h*i/4;x.strokeStyle='rgba(145,167,191,.15)';x.beginPath();x.moveTo(pad.l,y);x.lineTo(pad.l+w,y);x.stroke();x.fillStyle='#91a7bf';x.textAlign='right';x.fillText(money(v).replace('.00',''),pad.l-8,y+4)}x.strokeStyle='#4d8dff';x.lineWidth=3;x.lineCap='round';x.lineJoin='round';x.beginPath();pts.forEach((p,i)=>i?x.lineTo(xx(i),yy(p.value)):x.moveTo(xx(i),yy(p.value)));x.stroke();const g=x.createLinearGradient(0,pad.t,0,pad.t+h);g.addColorStop(0,'rgba(77,141,255,.25)');g.addColorStop(1,'rgba(77,141,255,0)');x.fillStyle=g;x.beginPath();pts.forEach((p,i)=>i?x.lineTo(xx(i),yy(p.value)):x.moveTo(xx(i),yy(p.value)));x.lineTo(xx(pts.length-1),pad.t+h);x.lineTo(xx(0),pad.t+h);x.closePath();x.fill();x.fillStyle=pts.at(-1).value>=settings.startingBankroll?'#2bd38b':'#ff647c';x.beginPath();x.arc(xx(pts.length-1),yy(pts.at(-1).value),5,0,Math.PI*2);x.fill();x.fillStyle='#91a7bf';x.textAlign='center';[0,Math.floor((pts.length-1)/2),pts.length-1].filter((v,i,a)=>a.indexOf(v)===i).forEach(i=>x.fillText(dateFmt(pts[i].date),xx(i),r.height-11))}
function filterOptions(id,field,label){const el=$(id),old=el.value,vals=[...new Set(bets.map(b=>b[field]).filter(Boolean))].sort();el.innerHTML=`<option value="">All ${label}</option>`+vals.map(v=>`<option>${esc(v)}</option>`).join('');el.value=old}
function filtered(){const q=$('searchFilter').value.toLowerCase(),sp=$('sportFilter').value,re=$('resultFilter').value,ma=$('marketFilter').value,bo=$('bookFilter').value,days=$('rangeFilter').value,cut=days==='all'?null:new Date(Date.now()-+days*86400000);return bets.filter(b=>(!q||[b.event,b.selection,b.sportsbook,b.notes].join(' ').toLowerCase().includes(q))&&(!sp||b.sport===sp)&&(!re||b.result===re)&&(!ma||b.betType===ma)&&(!bo||b.sportsbook===bo)&&(!cut||new Date(`${b.date}T23:59:59`)>=cut)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)}
function renderTable(){filterOptions('sportFilter','sport','sports');filterOptions('marketFilter','betType','markets');filterOptions('bookFilter','sportsbook','books');const list=filtered();$('visibleCount').textContent=`${list.length} bets`;$('emptyState').classList.toggle('hidden',!!list.length);$('betRows').innerHTML=list.map(b=>{const p=pl(b),cv=clv(b);return `<tr><td>${dateFmt(b.date)}</td><td>${esc(b.sport)}</td><td><strong>${esc(b.event)}</strong><br><span style="color:var(--muted);font-size:.72rem">${esc(b.betType)} · ${esc(b.selection)}</span></td><td>${esc(b.sportsbook||'—')}</td><td>${b.odds>0?'+':''}${b.odds}</td><td>${b.closingOdds?`${b.closingOdds>0?'+':''}${b.closingOdds}`:'—'}</td><td>${money(b.stake)}</td><td>${(+b.stake/+settings.unitSize).toFixed(2)}</td><td><span class="badge ${b.result.toLowerCase()}">${b.result}</span></td><td class="${cls(p)}"><strong>${b.result==='Pending'?'—':signed(p)}</strong></td><td class="${cv==null?'':cls(cv)}">${cv==null?'—':`${cv>0?'+':''}${cv.toFixed(2)}%`}</td><td><div class="row-actions"><button class="icon" onclick="editBet('${b.id}')">Edit</button><button class="icon delete" onclick="deleteBet('${b.id}')">Delete</button></div></td></tr>`}).join('')}
function renderMonthly(){const groups={};settled().forEach(b=>{const k=b.date.slice(0,7);(groups[k]??=[]).push(b)});$('monthlyRows').innerHTML=Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).map(([k,v])=>{const s=stats(v),label=new Date(`${k}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'});return `<tr><td>${label}</td><td>${v.length}</td><td>${s.wins}-${s.losses}-${s.pushes}</td><td>${money(s.stake)}</td><td class="${cls(s.profit)}"><strong>${signed(s.profit)}</strong></td><td class="${cls(s.roi)}">${pct(s.roi)}</td></tr>`}).join('')||'<tr><td colspan="6">No settled bets.</td></tr>';const vals=settled().map(clv).filter(v=>v!==null),pos=vals.filter(v=>v>0).length,avg=avgClv();$('clvReport').innerHTML=vals.length?`<article class="metric"><label>Average CLV</label><strong class="${cls(avg)}">${avg>0?'+':''}${pct(avg)}</strong><small>${pos} of ${vals.length} bets beat the close</small></article><div class="insight">Positive CLV generally indicates you captured a better price than the market's closing number.</div>`:'<div class="empty">Add closing odds to settled bets to calculate CLV.</div>'}
function render(){renderMetrics();renderPulse();renderRanks();renderTable();renderMonthly();requestAnimationFrame(renderChart)}
$('date').value=new Date().toISOString().slice(0,10);['result','stake','odds'].forEach(id=>$(id).addEventListener('input',()=>{const r=$('result').value,s=+$('stake').value,o=+$('odds').value;$('payout').value=r==='Win'?(s+potential(s,o)).toFixed(2):r==='Push'?s.toFixed(2):r==='Loss'?'0.00':''}));
$('betForm').addEventListener('submit',e=>{e.preventDefault();if(!validateBetForm())return;const wasEditing=!!editingId,o=Object.fromEntries(new FormData(e.currentTarget).entries());['odds','stake','payout','closingOdds'].forEach(k=>o[k]=o[k]===''?0:+o[k]);if(o.result==='Win'&&!o.payout)o.payout=+(o.stake+potential(o.stake,o.odds)).toFixed(2);if(o.result==='Push'&&!o.payout)o.payout=o.stake;o.id=editingId||uid();o.createdAt=editingId?(bets.find(b=>b.id===editingId)?.createdAt||Date.now()):Date.now();bets=editingId?bets.map(b=>b.id===editingId?o:b):[...bets,o];const persisted=save();resetForm();render();document.querySelector('[data-view="bets"]').click();toast(`${wasEditing?'Bet updated':'Bet saved'}${persisted?' — syncing automatically':' for this session only — browser storage is blocked.'}`,persisted?'success':'error')});
function resetForm(){document.querySelectorAll('.field-error').forEach(x=>x.remove());$('betForm').reset();$('date').value=new Date().toISOString().slice(0,10);editingId=null;$('formTitle').textContent='Add a bet';$('submitBtn').textContent='Save bet';$('cancelBtn').classList.add('hidden')}$('cancelBtn').onclick=resetForm;
window.editBet=id=>{const b=bets.find(x=>x.id===id);if(!b)return;editingId=id;Object.keys(b).forEach(k=>{if($(k))$(k).value=b[k]??''});$('formTitle').textContent='Edit bet';$('submitBtn').textContent='Update bet';$('cancelBtn').classList.remove('hidden');document.querySelector('[data-view="bets"]').click();scrollTo({top:0,behavior:'smooth'})};window.deleteBet=id=>{if(confirm('Delete this bet?')){bets=bets.filter(b=>b.id!==id);save();render()}};
const pageCopy={dashboard:['Dashboard','Overview of your bankroll, performance and recent bets.'],bets:['Bets','Add, grade, search and manage your wagers.'],analytics:['Analytics','Review ROI, CLV and performance breakdowns.'],settings:['Settings','Manage bankroll, backups and Cloudflare sync.']};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.view).classList.add('active');$('pageTitle').textContent=pageCopy[t.dataset.view][0];$('pageSubtitle').textContent=pageCopy[t.dataset.view][1];if(t.dataset.view==='dashboard')requestAnimationFrame(renderChart)});['searchFilter','sportFilter','resultFilter','marketFilter','bookFilter','rangeFilter'].forEach(id=>$(id).addEventListener('input',renderTable));addEventListener('resize',()=>document.querySelector('#dashboard.active')&&renderChart());
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function backup(){download(`betledger-pro-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:2,exportedAt:new Date().toISOString(),settings,bets},null,2),'application/json')}function csv(){if(!bets.length)return alert('No bets to export.');const h=['date','sport','event','betType','sportsbook','selection','odds','stake','closingOdds','timing','result','payout','notes'],cell=v=>{const s=String(v??'').replace(/"/g,'""');return /[",\n]/.test(s)?`"${s}"`:s};download(`betledger-pro-${new Date().toISOString().slice(0,10)}.csv`,[h.join(','),...bets.map(b=>h.map(k=>cell(b[k])).join(','))].join('\n'),'text/csv')}
$('cloudBtn').onclick=()=>document.querySelector('[data-view="settings"]').click();$('signOutBtn').onclick=async()=>{try{await api('logout',{method:'POST'});}finally{currentUser=null;bets=[];clearInterval(cloudPollTimer);$('userChip').classList.add('hidden');$('loginGate').classList.remove('hidden');render();}};$('pullCloudBtn').onclick=()=>pullCloudState(true);$('jsonExportBtn').onclick=backup;$('settingsBackupBtn').onclick=backup;$('csvExportBtn').onclick=csv;$('settingsCsvBtn').onclick=csv;$('jsonImportBtn').onclick=()=>$('jsonFile').click();$('jsonFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.bets))throw Error('Invalid backup');if(!confirm(`Replace current data with ${d.bets.length} bets from this backup?`))return;bets=d.bets;settings={...settings,...d.settings};save();syncSettings();render();alert('Backup restored.')}catch(err){alert(`Restore failed: ${err.message}`)}e.target.value=''};
function syncSettings(){$('startingBankroll').value=settings.startingBankroll;$('unitSize').value=settings.unitSize}syncSettings();$('saveSettingsBtn').onclick=()=>{settings.startingBankroll=Math.max(0,+$('startingBankroll').value||0);settings.unitSize=Math.max(.01,+$('unitSize').value||10);save();render();alert('Settings saved.')};$('resetBtn').onclick=()=>{if(confirm('Delete all bets and restore default settings?')){bets=[];settings={startingBankroll:1000,unitSize:10};save();syncSettings();resetForm();render()}};
$('demoBtn').onclick=()=>{if(bets.length&&!confirm('Add demo data to your existing ledger?'))return;const d=n=>new Date(Date.now()-n*86400000).toISOString().slice(0,10),raw=[[42,'MLB','Cubs at Cardinals','Moneyline','DraftKings','Cubs ML',125,40,115,'Pregame','Win',90],[37,'NBA','Knicks at Celtics','Spread / Run Line','FanDuel','Knicks +5.5',-110,55,-118,'Pregame','Loss',0],[31,'MLB','Dodgers at Padres','Player Prop','BetMGM','Ohtani O1.5 TB',105,50,-105,'Pregame','Win',102.5],[24,'NFL','Packers at Bears','Total','Caesars','Under 44.5',-115,60,-110,'Pregame','Push',60],[18,'NHL','Stars at Avalanche','Moneyline','DraftKings','Avalanche ML',-135,67.5,-150,'Pregame','Win',117.5],[12,'MLB','Mets at Phillies','Parlay','FanDuel','Phillies ML + O7.5',220,35,200,'Pregame','Loss',0],[6,'NBA','Lakers at Suns','Live Bet','ESPN BET','Suns +3.5',-105,45,-120,'Live','Win',87.86],[0,'MLB','Mariners at Astros','Player Prop','Fanatics','Rodríguez O1.5 TB',115,45,0,'Pregame','Pending',0]];bets.push(...raw.map(x=>({id:uid(),createdAt:Date.now(),date:d(x[0]),sport:x[1],event:x[2],betType:x[3],sportsbook:x[4],selection:x[5],odds:x[6],stake:x[7],closingOdds:x[8],timing:x[9],result:x[10],payout:x[11],notes:''})));save();render()};
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const user=$('loginUser').value,password=$('loginPassword').value,msg=$('loginMessage');msg.textContent='Signing in…';try{const data=await api('login',{method:'POST',body:JSON.stringify({user,password})});$('loginPassword').value='';msg.textContent='';await establishSession(data.user)}catch(err){msg.textContent=err.message}});render();initCloud();
